branch: 'main'
repoUrl: 'https://github.com/Sharvari134/cassandra.git'
approvalMessage: 'Do you want to proceed with Ansible Playbook execution?'
approvalButton: 'Proceed'
playbookPath: 'install.yml'
inventory: 'inventory.ini'
slackChannel: 'jenkins'
successMessage: 'Pipeline Job Succeeded'
failureMessage: 'Pipeline Job Failed'
unstableMessage: 'Pipeline Job is Unstable'
